sonar.projectKey=shsdbd_RVC_Test
sonar.organization=shsdbd

# 분석할 소스 및 테스트 경로
sonar.sources=src
sonar.tests=tests

# 인코딩 및 언어 설정
sonar.sourceEncoding=UTF-8
sonar.language=cpp

# 빌드 및 커버리지 정보 연결
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.cpp.llvm.cov.reportPath=coverage_report.txt